name: Deployment

on:
  push:
    branches: [ main, dev, feature/teste-ci ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deploy Simulation
      run: echo "Deploy realizado com sucesso!"
